### ISSUE TITLE
Null check operator exception in showToastWidget

### ISSUE THREAD

**Issue by cswkim** [bdlukaa/fl_toast#1]
I'm receiving `Unhandled Exception: Null check operator used on a null value` here:

https://github.com/bdlukaa/fl_toast/blob/master/lib/src/toast.dart#L60

I'm on Flutter `v2.0.4`, sdk `">=2.12.0-0 <3.0.0"` and fl_toast `3.0.1`

**Comment by bdlukaa** [comment]
You need to make sure there's a `Overlay` widget above the `context`. It's provided by the `MaterialApp`.

**Comment by bdlukaa** [comment]
Can you show your code?

**Comment by cswkim** [comment]
> You need to make sure there's a `Overlay` widget above the `context`. It's provided by the `MaterialApp`.

Ah I didn't know that.
