### ISSUE TITLE
Screen is disabled when Toast is present

### ISSUE THREAD

**Issue by hyped0001** [bdlukaa/fl_toast#4]
Does anyone else have the issue where you cannot do anything on the rest of the screen while the Toast is present? I cannot scroll/click anything while the Toast is open. I'm not sure if its something with my Toast or the library in general.

**Comment by bdlukaa** [comment]
It may be the case that your toast is occupying the entire screen, blocking the widgets behind it. It can be resolved by wrapping the toast in an `Align` widget and providing the `alignment`
